/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/_setup'
import { Route as AuthenticatedSetupRegisterEntityRouteImport } from './routes/_authenticated/_setup/register-entity'
import { Route as AuthenticatedSetupOrgDepartmentsRouteImport } from './routes/_authenticated/_setup/org-departments'
import { Route as AuthenticatedSetupEmployeeUploadRouteImport } from './routes/_authenticated/_setup/employee-upload'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/_setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetupRegisterEntityRoute =
  AuthenticatedSetupRegisterEntityRouteImport.update({
    id: '/register-entity',
    path: '/register-entity',
    getParentRoute: () => AuthenticatedSetupRoute,
  } as any)
const AuthenticatedSetupOrgDepartmentsRoute =
  AuthenticatedSetupOrgDepartmentsRouteImport.update({
    id: '/org-departments',
    path: '/org-departments',
    getParentRoute: () => AuthenticatedSetupRoute,
  } as any)
const AuthenticatedSetupEmployeeUploadRoute =
  AuthenticatedSetupEmployeeUploadRouteImport.update({
    id: '/employee-upload',
    path: '/employee-upload',
    getParentRoute: () => AuthenticatedSetupRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/employee-upload': typeof AuthenticatedSetupEmployeeUploadRoute
  '/org-departments': typeof AuthenticatedSetupOrgDepartmentsRoute
  '/register-entity': typeof AuthenticatedSetupRegisterEntityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/employee-upload': typeof AuthenticatedSetupEmployeeUploadRoute
  '/org-departments': typeof AuthenticatedSetupOrgDepartmentsRoute
  '/register-entity': typeof AuthenticatedSetupRegisterEntityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_setup': typeof AuthenticatedSetupRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/_setup/employee-upload': typeof AuthenticatedSetupEmployeeUploadRoute
  '/_authenticated/_setup/org-departments': typeof AuthenticatedSetupOrgDepartmentsRoute
  '/_authenticated/_setup/register-entity': typeof AuthenticatedSetupRegisterEntityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/setup'
    | '/employee-upload'
    | '/org-departments'
    | '/register-entity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/setup'
    | '/employee-upload'
    | '/org-departments'
    | '/register-entity'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_setup'
    | '/_authenticated/dashboard'
    | '/_authenticated/setup'
    | '/_authenticated/_setup/employee-upload'
    | '/_authenticated/_setup/org-departments'
    | '/_authenticated/_setup/register-entity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_setup': {
      id: '/_authenticated/_setup'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_setup/register-entity': {
      id: '/_authenticated/_setup/register-entity'
      path: '/register-entity'
      fullPath: '/register-entity'
      preLoaderRoute: typeof AuthenticatedSetupRegisterEntityRouteImport
      parentRoute: typeof AuthenticatedSetupRoute
    }
    '/_authenticated/_setup/org-departments': {
      id: '/_authenticated/_setup/org-departments'
      path: '/org-departments'
      fullPath: '/org-departments'
      preLoaderRoute: typeof AuthenticatedSetupOrgDepartmentsRouteImport
      parentRoute: typeof AuthenticatedSetupRoute
    }
    '/_authenticated/_setup/employee-upload': {
      id: '/_authenticated/_setup/employee-upload'
      path: '/employee-upload'
      fullPath: '/employee-upload'
      preLoaderRoute: typeof AuthenticatedSetupEmployeeUploadRouteImport
      parentRoute: typeof AuthenticatedSetupRoute
    }
  }
}

interface AuthenticatedSetupRouteChildren {
  AuthenticatedSetupEmployeeUploadRoute: typeof AuthenticatedSetupEmployeeUploadRoute
  AuthenticatedSetupOrgDepartmentsRoute: typeof AuthenticatedSetupOrgDepartmentsRoute
  AuthenticatedSetupRegisterEntityRoute: typeof AuthenticatedSetupRegisterEntityRoute
}

const AuthenticatedSetupRouteChildren: AuthenticatedSetupRouteChildren = {
  AuthenticatedSetupEmployeeUploadRoute: AuthenticatedSetupEmployeeUploadRoute,
  AuthenticatedSetupOrgDepartmentsRoute: AuthenticatedSetupOrgDepartmentsRoute,
  AuthenticatedSetupRegisterEntityRoute: AuthenticatedSetupRegisterEntityRoute,
}

const AuthenticatedSetupRouteWithChildren =
  AuthenticatedSetupRoute._addFileChildren(AuthenticatedSetupRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSetupRoute: AuthenticatedSetupRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
