/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedRegisterEntityRouteImport } from './routes/_authenticated/register-entity'
import { Route as AuthenticatedOrgDepartmentsRouteImport } from './routes/_authenticated/org-departments'
import { Route as AuthenticatedEmployeeUploadRouteImport } from './routes/_authenticated/employee-upload'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegisterEntityRoute =
  AuthenticatedRegisterEntityRouteImport.update({
    id: '/register-entity',
    path: '/register-entity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgDepartmentsRoute =
  AuthenticatedOrgDepartmentsRouteImport.update({
    id: '/org-departments',
    path: '/org-departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeeUploadRoute =
  AuthenticatedEmployeeUploadRouteImport.update({
    id: '/employee-upload',
    path: '/employee-upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employee-upload': typeof AuthenticatedEmployeeUploadRoute
  '/org-departments': typeof AuthenticatedOrgDepartmentsRoute
  '/register-entity': typeof AuthenticatedRegisterEntityRoute
  '/setup': typeof AuthenticatedSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employee-upload': typeof AuthenticatedEmployeeUploadRoute
  '/org-departments': typeof AuthenticatedOrgDepartmentsRoute
  '/register-entity': typeof AuthenticatedRegisterEntityRoute
  '/setup': typeof AuthenticatedSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employee-upload': typeof AuthenticatedEmployeeUploadRoute
  '/_authenticated/org-departments': typeof AuthenticatedOrgDepartmentsRoute
  '/_authenticated/register-entity': typeof AuthenticatedRegisterEntityRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/employee-upload'
    | '/org-departments'
    | '/register-entity'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/employee-upload'
    | '/org-departments'
    | '/register-entity'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/employee-upload'
    | '/_authenticated/org-departments'
    | '/_authenticated/register-entity'
    | '/_authenticated/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/register-entity': {
      id: '/_authenticated/register-entity'
      path: '/register-entity'
      fullPath: '/register-entity'
      preLoaderRoute: typeof AuthenticatedRegisterEntityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org-departments': {
      id: '/_authenticated/org-departments'
      path: '/org-departments'
      fullPath: '/org-departments'
      preLoaderRoute: typeof AuthenticatedOrgDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employee-upload': {
      id: '/_authenticated/employee-upload'
      path: '/employee-upload'
      fullPath: '/employee-upload'
      preLoaderRoute: typeof AuthenticatedEmployeeUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeeUploadRoute: typeof AuthenticatedEmployeeUploadRoute
  AuthenticatedOrgDepartmentsRoute: typeof AuthenticatedOrgDepartmentsRoute
  AuthenticatedRegisterEntityRoute: typeof AuthenticatedRegisterEntityRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeeUploadRoute: AuthenticatedEmployeeUploadRoute,
  AuthenticatedOrgDepartmentsRoute: AuthenticatedOrgDepartmentsRoute,
  AuthenticatedRegisterEntityRoute: AuthenticatedRegisterEntityRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
