/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWeightingAssignmentRouteImport } from './routes/_authenticated/weighting-assignment'
import { Route as AuthenticatedUploadHistoryRouteImport } from './routes/_authenticated/upload-history'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedKpiBoardRouteImport } from './routes/_authenticated/kpi-board'
import { Route as AuthenticatedKpiApprovalsRouteImport } from './routes/_authenticated/kpi-approvals'
import { Route as AuthenticatedIndividualKpisRouteImport } from './routes/_authenticated/individual-kpis'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBonusSchemesRouteImport } from './routes/_authenticated/bonus-schemes'
import { Route as AuthenticatedBonusAssignmentsRouteImport } from './routes/_authenticated/bonus-assignments'
import { Route as AuthenticatedActualsUploadRouteImport } from './routes/_authenticated/actuals-upload'
import { Route as AuthenticatedSetupLayoutRouteImport } from './routes/_authenticated/_setupLayout'
import { Route as AuthenticatedSetupLayoutRoleAssignmentRouteImport } from './routes/_authenticated/_setupLayout/role-assignment'
import { Route as AuthenticatedSetupLayoutRegisterEntityRouteImport } from './routes/_authenticated/_setupLayout/register-entity'
import { Route as AuthenticatedSetupLayoutOrgDepartmentsRouteImport } from './routes/_authenticated/_setupLayout/org-departments'
import { Route as AuthenticatedSetupLayoutEmployeeUploadRouteImport } from './routes/_authenticated/_setupLayout/employee-upload'
import { Route as AuthenticatedSetupLayoutDriverWeightingsRouteImport } from './routes/_authenticated/_setupLayout/driver-weightings'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeightingAssignmentRoute =
  AuthenticatedWeightingAssignmentRouteImport.update({
    id: '/weighting-assignment',
    path: '/weighting-assignment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUploadHistoryRoute =
  AuthenticatedUploadHistoryRouteImport.update({
    id: '/upload-history',
    path: '/upload-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKpiBoardRoute = AuthenticatedKpiBoardRouteImport.update({
  id: '/kpi-board',
  path: '/kpi-board',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKpiApprovalsRoute =
  AuthenticatedKpiApprovalsRouteImport.update({
    id: '/kpi-approvals',
    path: '/kpi-approvals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIndividualKpisRoute =
  AuthenticatedIndividualKpisRouteImport.update({
    id: '/individual-kpis',
    path: '/individual-kpis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBonusSchemesRoute =
  AuthenticatedBonusSchemesRouteImport.update({
    id: '/bonus-schemes',
    path: '/bonus-schemes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBonusAssignmentsRoute =
  AuthenticatedBonusAssignmentsRouteImport.update({
    id: '/bonus-assignments',
    path: '/bonus-assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActualsUploadRoute =
  AuthenticatedActualsUploadRouteImport.update({
    id: '/actuals-upload',
    path: '/actuals-upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSetupLayoutRoute =
  AuthenticatedSetupLayoutRouteImport.update({
    id: '/_setupLayout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSetupLayoutRoleAssignmentRoute =
  AuthenticatedSetupLayoutRoleAssignmentRouteImport.update({
    id: '/role-assignment',
    path: '/role-assignment',
    getParentRoute: () => AuthenticatedSetupLayoutRoute,
  } as any)
const AuthenticatedSetupLayoutRegisterEntityRoute =
  AuthenticatedSetupLayoutRegisterEntityRouteImport.update({
    id: '/register-entity',
    path: '/register-entity',
    getParentRoute: () => AuthenticatedSetupLayoutRoute,
  } as any)
const AuthenticatedSetupLayoutOrgDepartmentsRoute =
  AuthenticatedSetupLayoutOrgDepartmentsRouteImport.update({
    id: '/org-departments',
    path: '/org-departments',
    getParentRoute: () => AuthenticatedSetupLayoutRoute,
  } as any)
const AuthenticatedSetupLayoutEmployeeUploadRoute =
  AuthenticatedSetupLayoutEmployeeUploadRouteImport.update({
    id: '/employee-upload',
    path: '/employee-upload',
    getParentRoute: () => AuthenticatedSetupLayoutRoute,
  } as any)
const AuthenticatedSetupLayoutDriverWeightingsRoute =
  AuthenticatedSetupLayoutDriverWeightingsRouteImport.update({
    id: '/driver-weightings',
    path: '/driver-weightings',
    getParentRoute: () => AuthenticatedSetupLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faqs': typeof FaqsRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/support': typeof SupportRoute
  '/actuals-upload': typeof AuthenticatedActualsUploadRoute
  '/bonus-assignments': typeof AuthenticatedBonusAssignmentsRoute
  '/bonus-schemes': typeof AuthenticatedBonusSchemesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/individual-kpis': typeof AuthenticatedIndividualKpisRoute
  '/kpi-approvals': typeof AuthenticatedKpiApprovalsRoute
  '/kpi-board': typeof AuthenticatedKpiBoardRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/upload-history': typeof AuthenticatedUploadHistoryRoute
  '/weighting-assignment': typeof AuthenticatedWeightingAssignmentRoute
  '/driver-weightings': typeof AuthenticatedSetupLayoutDriverWeightingsRoute
  '/employee-upload': typeof AuthenticatedSetupLayoutEmployeeUploadRoute
  '/org-departments': typeof AuthenticatedSetupLayoutOrgDepartmentsRoute
  '/register-entity': typeof AuthenticatedSetupLayoutRegisterEntityRoute
  '/role-assignment': typeof AuthenticatedSetupLayoutRoleAssignmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faqs': typeof FaqsRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/support': typeof SupportRoute
  '/actuals-upload': typeof AuthenticatedActualsUploadRoute
  '/bonus-assignments': typeof AuthenticatedBonusAssignmentsRoute
  '/bonus-schemes': typeof AuthenticatedBonusSchemesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/individual-kpis': typeof AuthenticatedIndividualKpisRoute
  '/kpi-approvals': typeof AuthenticatedKpiApprovalsRoute
  '/kpi-board': typeof AuthenticatedKpiBoardRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/upload-history': typeof AuthenticatedUploadHistoryRoute
  '/weighting-assignment': typeof AuthenticatedWeightingAssignmentRoute
  '/driver-weightings': typeof AuthenticatedSetupLayoutDriverWeightingsRoute
  '/employee-upload': typeof AuthenticatedSetupLayoutEmployeeUploadRoute
  '/org-departments': typeof AuthenticatedSetupLayoutOrgDepartmentsRoute
  '/register-entity': typeof AuthenticatedSetupLayoutRegisterEntityRoute
  '/role-assignment': typeof AuthenticatedSetupLayoutRoleAssignmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/faqs': typeof FaqsRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/support': typeof SupportRoute
  '/_authenticated/_setupLayout': typeof AuthenticatedSetupLayoutRouteWithChildren
  '/_authenticated/actuals-upload': typeof AuthenticatedActualsUploadRoute
  '/_authenticated/bonus-assignments': typeof AuthenticatedBonusAssignmentsRoute
  '/_authenticated/bonus-schemes': typeof AuthenticatedBonusSchemesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/individual-kpis': typeof AuthenticatedIndividualKpisRoute
  '/_authenticated/kpi-approvals': typeof AuthenticatedKpiApprovalsRoute
  '/_authenticated/kpi-board': typeof AuthenticatedKpiBoardRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/upload-history': typeof AuthenticatedUploadHistoryRoute
  '/_authenticated/weighting-assignment': typeof AuthenticatedWeightingAssignmentRoute
  '/_authenticated/_setupLayout/driver-weightings': typeof AuthenticatedSetupLayoutDriverWeightingsRoute
  '/_authenticated/_setupLayout/employee-upload': typeof AuthenticatedSetupLayoutEmployeeUploadRoute
  '/_authenticated/_setupLayout/org-departments': typeof AuthenticatedSetupLayoutOrgDepartmentsRoute
  '/_authenticated/_setupLayout/register-entity': typeof AuthenticatedSetupLayoutRegisterEntityRoute
  '/_authenticated/_setupLayout/role-assignment': typeof AuthenticatedSetupLayoutRoleAssignmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faqs'
    | '/language'
    | '/login'
    | '/support'
    | '/actuals-upload'
    | '/bonus-assignments'
    | '/bonus-schemes'
    | '/dashboard'
    | '/individual-kpis'
    | '/kpi-approvals'
    | '/kpi-board'
    | '/setup'
    | '/upload-history'
    | '/weighting-assignment'
    | '/driver-weightings'
    | '/employee-upload'
    | '/org-departments'
    | '/register-entity'
    | '/role-assignment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faqs'
    | '/language'
    | '/login'
    | '/support'
    | '/actuals-upload'
    | '/bonus-assignments'
    | '/bonus-schemes'
    | '/dashboard'
    | '/individual-kpis'
    | '/kpi-approvals'
    | '/kpi-board'
    | '/setup'
    | '/upload-history'
    | '/weighting-assignment'
    | '/driver-weightings'
    | '/employee-upload'
    | '/org-departments'
    | '/register-entity'
    | '/role-assignment'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/faqs'
    | '/language'
    | '/login'
    | '/support'
    | '/_authenticated/_setupLayout'
    | '/_authenticated/actuals-upload'
    | '/_authenticated/bonus-assignments'
    | '/_authenticated/bonus-schemes'
    | '/_authenticated/dashboard'
    | '/_authenticated/individual-kpis'
    | '/_authenticated/kpi-approvals'
    | '/_authenticated/kpi-board'
    | '/_authenticated/setup'
    | '/_authenticated/upload-history'
    | '/_authenticated/weighting-assignment'
    | '/_authenticated/_setupLayout/driver-weightings'
    | '/_authenticated/_setupLayout/employee-upload'
    | '/_authenticated/_setupLayout/org-departments'
    | '/_authenticated/_setupLayout/register-entity'
    | '/_authenticated/_setupLayout/role-assignment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  FaqsRoute: typeof FaqsRoute
  LanguageRoute: typeof LanguageRoute
  LoginRoute: typeof LoginRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weighting-assignment': {
      id: '/_authenticated/weighting-assignment'
      path: '/weighting-assignment'
      fullPath: '/weighting-assignment'
      preLoaderRoute: typeof AuthenticatedWeightingAssignmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload-history': {
      id: '/_authenticated/upload-history'
      path: '/upload-history'
      fullPath: '/upload-history'
      preLoaderRoute: typeof AuthenticatedUploadHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kpi-board': {
      id: '/_authenticated/kpi-board'
      path: '/kpi-board'
      fullPath: '/kpi-board'
      preLoaderRoute: typeof AuthenticatedKpiBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kpi-approvals': {
      id: '/_authenticated/kpi-approvals'
      path: '/kpi-approvals'
      fullPath: '/kpi-approvals'
      preLoaderRoute: typeof AuthenticatedKpiApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/individual-kpis': {
      id: '/_authenticated/individual-kpis'
      path: '/individual-kpis'
      fullPath: '/individual-kpis'
      preLoaderRoute: typeof AuthenticatedIndividualKpisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bonus-schemes': {
      id: '/_authenticated/bonus-schemes'
      path: '/bonus-schemes'
      fullPath: '/bonus-schemes'
      preLoaderRoute: typeof AuthenticatedBonusSchemesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bonus-assignments': {
      id: '/_authenticated/bonus-assignments'
      path: '/bonus-assignments'
      fullPath: '/bonus-assignments'
      preLoaderRoute: typeof AuthenticatedBonusAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actuals-upload': {
      id: '/_authenticated/actuals-upload'
      path: '/actuals-upload'
      fullPath: '/actuals-upload'
      preLoaderRoute: typeof AuthenticatedActualsUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_setupLayout': {
      id: '/_authenticated/_setupLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSetupLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_setupLayout/role-assignment': {
      id: '/_authenticated/_setupLayout/role-assignment'
      path: '/role-assignment'
      fullPath: '/role-assignment'
      preLoaderRoute: typeof AuthenticatedSetupLayoutRoleAssignmentRouteImport
      parentRoute: typeof AuthenticatedSetupLayoutRoute
    }
    '/_authenticated/_setupLayout/register-entity': {
      id: '/_authenticated/_setupLayout/register-entity'
      path: '/register-entity'
      fullPath: '/register-entity'
      preLoaderRoute: typeof AuthenticatedSetupLayoutRegisterEntityRouteImport
      parentRoute: typeof AuthenticatedSetupLayoutRoute
    }
    '/_authenticated/_setupLayout/org-departments': {
      id: '/_authenticated/_setupLayout/org-departments'
      path: '/org-departments'
      fullPath: '/org-departments'
      preLoaderRoute: typeof AuthenticatedSetupLayoutOrgDepartmentsRouteImport
      parentRoute: typeof AuthenticatedSetupLayoutRoute
    }
    '/_authenticated/_setupLayout/employee-upload': {
      id: '/_authenticated/_setupLayout/employee-upload'
      path: '/employee-upload'
      fullPath: '/employee-upload'
      preLoaderRoute: typeof AuthenticatedSetupLayoutEmployeeUploadRouteImport
      parentRoute: typeof AuthenticatedSetupLayoutRoute
    }
    '/_authenticated/_setupLayout/driver-weightings': {
      id: '/_authenticated/_setupLayout/driver-weightings'
      path: '/driver-weightings'
      fullPath: '/driver-weightings'
      preLoaderRoute: typeof AuthenticatedSetupLayoutDriverWeightingsRouteImport
      parentRoute: typeof AuthenticatedSetupLayoutRoute
    }
  }
}

interface AuthenticatedSetupLayoutRouteChildren {
  AuthenticatedSetupLayoutDriverWeightingsRoute: typeof AuthenticatedSetupLayoutDriverWeightingsRoute
  AuthenticatedSetupLayoutEmployeeUploadRoute: typeof AuthenticatedSetupLayoutEmployeeUploadRoute
  AuthenticatedSetupLayoutOrgDepartmentsRoute: typeof AuthenticatedSetupLayoutOrgDepartmentsRoute
  AuthenticatedSetupLayoutRegisterEntityRoute: typeof AuthenticatedSetupLayoutRegisterEntityRoute
  AuthenticatedSetupLayoutRoleAssignmentRoute: typeof AuthenticatedSetupLayoutRoleAssignmentRoute
}

const AuthenticatedSetupLayoutRouteChildren: AuthenticatedSetupLayoutRouteChildren =
  {
    AuthenticatedSetupLayoutDriverWeightingsRoute:
      AuthenticatedSetupLayoutDriverWeightingsRoute,
    AuthenticatedSetupLayoutEmployeeUploadRoute:
      AuthenticatedSetupLayoutEmployeeUploadRoute,
    AuthenticatedSetupLayoutOrgDepartmentsRoute:
      AuthenticatedSetupLayoutOrgDepartmentsRoute,
    AuthenticatedSetupLayoutRegisterEntityRoute:
      AuthenticatedSetupLayoutRegisterEntityRoute,
    AuthenticatedSetupLayoutRoleAssignmentRoute:
      AuthenticatedSetupLayoutRoleAssignmentRoute,
  }

const AuthenticatedSetupLayoutRouteWithChildren =
  AuthenticatedSetupLayoutRoute._addFileChildren(
    AuthenticatedSetupLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSetupLayoutRoute: typeof AuthenticatedSetupLayoutRouteWithChildren
  AuthenticatedActualsUploadRoute: typeof AuthenticatedActualsUploadRoute
  AuthenticatedBonusAssignmentsRoute: typeof AuthenticatedBonusAssignmentsRoute
  AuthenticatedBonusSchemesRoute: typeof AuthenticatedBonusSchemesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndividualKpisRoute: typeof AuthenticatedIndividualKpisRoute
  AuthenticatedKpiApprovalsRoute: typeof AuthenticatedKpiApprovalsRoute
  AuthenticatedKpiBoardRoute: typeof AuthenticatedKpiBoardRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedUploadHistoryRoute: typeof AuthenticatedUploadHistoryRoute
  AuthenticatedWeightingAssignmentRoute: typeof AuthenticatedWeightingAssignmentRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSetupLayoutRoute: AuthenticatedSetupLayoutRouteWithChildren,
  AuthenticatedActualsUploadRoute: AuthenticatedActualsUploadRoute,
  AuthenticatedBonusAssignmentsRoute: AuthenticatedBonusAssignmentsRoute,
  AuthenticatedBonusSchemesRoute: AuthenticatedBonusSchemesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndividualKpisRoute: AuthenticatedIndividualKpisRoute,
  AuthenticatedKpiApprovalsRoute: AuthenticatedKpiApprovalsRoute,
  AuthenticatedKpiBoardRoute: AuthenticatedKpiBoardRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedUploadHistoryRoute: AuthenticatedUploadHistoryRoute,
  AuthenticatedWeightingAssignmentRoute: AuthenticatedWeightingAssignmentRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  FaqsRoute: FaqsRoute,
  LanguageRoute: LanguageRoute,
  LoginRoute: LoginRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
